id = "lmy"
name = "lmy"
description = "lmy"
version = "0.0.1"
schema_version = 1
authors = ["Sarah Hawkless <abc@xyz.com>"]
repository = "https://github.com/orlaya/lmy_zed"

[grammars.lmy]
repository = "https://github.com/orlaya/lmy_tree"
commit = "ddd86608eb17b4bdf2af37056b1d940ea36037b5"
