name = "LMY"
grammar = "lmy"
path_suffixes = ["lmy"]
line_comments = ["// "]
tab_size = 2
brackets = [
    { start = "[", end = "]", close = true, newline = false },
    { start = "{", end = "}", close = true, newline = false },
]
